import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { getServerSession } from "next-auth/next";
import { NEXT_AUTH_CONFIG } from "@/lib/auth";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(NEXT_AUTH_CONFIG);
  return (
    <html lang="en">
      <head>
       <title>Merch Plus</title>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body >
       <Providers session={session}>
        {children}
       </Providers>
        </body>
    </html>
  );
}
